### ISSUE TITLE
Docker Container dies upon EHOSTUNREACH

### ISSUE THREAD

**Issue by new-gen23** [victronenergy/venus-docker#18]
Yesterday, all four containers died:  
venus-docker-grafana_server_1  
venus-docker-grafana_upnp_1  
venus-docker-grafana_influxdb_1  
venus-docker-grafana_graphing_1  

venus-docker-grafana_upnp_1 logs returned:  
```
{ FetchError: request to http://169.254.8.247:37619/com.victronenergy.ccgx.C0:61:9A:B1:ED:1B.xml failed, reason: connect EHOSTUNREACH 169.254.8.247:37619
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/venus-docker-grafana-server/node_modules/node-fetch/lib/index.js:1455:11)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
  message: 'request to http://169.254.8.247:37619/com.victronenergy.ccgx.C0:61:9A:B1:ED:1B.xml failed, reason: connect EHOSTUNREACH 169.254.8.247:37619',
  type: 'system',
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH' 
```

venus-docker-grafana_server_1 logs returned:  
```
[error] [venus-server] connect ECONNREFUSED 172.19.0.3:8086 Error: connect ECONNREFUSED 172.19.0.3:8086
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
[error] [upnp] FetchError: request to http://169.254.8.247:37619/com.victronenergy.ccgx.C0:61:9A:B1:ED:1B.xml failed, reason: connect EHOSTUNREACH 169.254.8.247:37619 
[error] [upnp] FetchError: request to http://169.254.8.247:37619/com.victronenergy.ccgx.C0:61:9A:B1:ED:1B.xml failed, reason: connect EHOSTUNREACH 169.254.8.247:37619 
[info] [influxdb] Attempting connection to influxdb:8086/venus 
[error] [venus-server] connect ECONNREFUSED 172.19.0.3:8086 Error: connect ECONNREFUSED 172.19.0.3:8086
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
[info] [influxdb] Attempting connection to influxdb:8086/venus 
[error] [venus-server] connect ECONNREFUSED 172.19.0.3:8086 Error: connect ECONNREFUSED 172.19.0.3:8086
```

I have no clue what caused the crash of the containers, but I observed gaps in the graphana graphs. The network do far is fine and the raspberry pi 4 pulling data from the cerbo gx is directly connected via a switch. Any help appreciated to debug the crash.

**Comment by martinbosma** [comment]
Seems to be wrong repo, see https://github.com/victronenergy/venus-grafana instead
